### ISSUE TITLE
user-given config to decide on map layer pattern

### ISSUE THREAD

**Issue by bsubei** [bsubei/squad_map_randomizer#1]
Currently, the map layer pattern is hard-coded into the script, which makes it hard to change the pattern quickly.

The config is just a yaml that takes in the field names it should filter by. Example config:
```
seeding_layers:
  - gamemode: Skirmish
  - gamemode: Skirmish
  - gamemode: Skirmish
pattern:
  - gamemode: AAS
    night: true
  - gamemode: RAAS
  - gamemode: AAS
    teams:
      - US
    helicopters: true
```
Having multiple fields for each map in the pattern implies an `AND` relationship between them. For example, the above config picks 3 skirmish maps for seeding (prefixed at the beginning), and then the pattern is 3 randomly chosen maps with these properties:
1- has gamemode `AAS` **AND** has night True (all the other fields are ignored so e.g. a layer with helicopters may or may not be chosen)
2- has gamemode RAAS
3- has gamemode AAS **AND** has helicopters **AND** has US team on any side (this one field is special and interpreted this way, all other fields are verbatim the same from the JSON layer file).

NOTE: all bugged layers are removed anyways implicitly so there's no need to include that field in the config (unless you want to explicitly enable bugged layers).

For reference, a typical map layer JSON object:
```
  {
    "map": "Al Basrah",
    "layer": "Al Basrah AAS v1",
    "gamemode": "AAS",
    "version": "v1",
    "team1": "US",
    "team2": "INS",
    "helicopters": false,
    "night": false,
    "RAA_Lanes": false,
    "Invasion_Random": false,
    "bugged": false
  },
```

**Comment by bsubei** [comment]
I forgot to include these things:
- the number of pattern repeats needs to be explicitly added as a root level key-val pair.
- `teams` should just be `team`
- all fields can accept **multiple** entries (e.g. the team field), and applies an OR within that one choice.
- the config for the mapvoter will just be a subset of this (or rather, just not bother including the seeding part and the number of repeats, all using default values)

**Comment by bsubei** [comment]
also forgot to mention a big motivator for this is being able to create patterns with a decent selection of maps based on **size**. Now that I've closed https://github.com/bsubei/squad_map_layers/issues/4 , it should be possible to filter layers based on map size

**Comment by bsubei** [comment]
another thing: possibly include the extra tags in the mapvoter choices without having to hardcode it in. e.g. if the config describes a choice/pattern as AAS and medium and US, then just put all those tags together in the string. e.g.
`Al Basrah AAS v1 (AAS, medium, US)`
If any of the fields are boolean, then instead of putting in `true`/`false`, just put the field name. e.g. for a map choice with RAAS and small and has helicopters true:
`blabla_map_name (RAAS, small, helicopters)`

NOTE: might just display the map name and not the layer name in the choices (especially if it comes with descriptions like that)

**Comment by bsubei** [comment]
## Example rotation config
```
seeding:
  - gamemode: Skirmish
  - gamemode: Skirmish
    team:
      - CAF
pattern_repeats: 5
pattern:
  - gamemode:
    - AAS
    - RAAS
    map_size: small
  - gamemode:
    - AAS
    - RAAS
    map_size: medium
  - gamemode:
    - AAS
    - RAAS
    map_size: medium
  - gamemode:
    - AAS
    - RAAS
    map_size: large
    helicopters: true
```
Description of the config:
- The first 2 maps are skirmish maps (the 2nd has CAF as one of the teams)
- The pattern (described next) is repeated 5 times.
- The pattern has 4 maps (all are either RAAS or AAS). The first is small sized, the second and third are medium sized, and the fourth is large sized and must have helicopters.


## Example voter config
```
pattern:
  - gamemode:
    - AAS
    - RAAS
    map_size: small
  - gamemode:
    - AAS
    - RAAS
    map_size: medium
  - gamemode:
    - AAS
    - RAAS
    map_size: medium
  - gamemode:
    - AAS
    - RAAS
    map_size: large
    helicopters: true
```
The voter config simply reuses the `pattern` part of the rotation config (after all it's just a small rotation where `pattern_repeats` is 1 and `seeding` is empty).
